name: build image

on:
  push:
    branches:
      - main

jobs:
  build_image:
    name: Build a container image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: set the build version (git hash)
        run: echo "BUILD_VERSION=$(git rev-parse --short $GITHUB_SHA)" >> $GITHUB_ENV

      - name: login to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Build the Container image
        run: docker build . --file Containerfile --tag ghcr.io/seungjin/logger:${{ env.BUILD_VERSION }} -t ghcr.io/seungjin/logger:latest

      - name: push the Docker image with version number
        run: |
          docker image push ghcr.io/seungjin/logger:${{ env.BUILD_VERSION }}
          docker image push ghcr.io/seungjin/logger:latest
